Calculate deformation etc without gui interface

In [1]:
import numpy as np

import pyqtgraph as pg
import pyqtgraph.Qt.QtGui as qtg
from cmm_error_map import data_cmpts as dc
from cmm_error_map import design_linear as design

In [11]:
cmm = dc.pmm_866
p0 = dc.Probe(title="P0", name="p0", length=qtg.QVector3D(0, 0, 0))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=dc.default_artefacts["KOBA 0620"],
    transform3d=pg.Transform3D(),
    probe=p0,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,
)
mmt.artefact.nballs = (5, 5)
model_params = dc.model_parameters_test.copy()
# mmt.recalculate(model_params, cmm.cmm_model)

In [22]:
xyzt = np.array([0.,0., 0.0])
dev3d = design.linear_model_point(np.array([100.,100.,100.]), xyzt, model_params, fixed_table=False, bridge_axis=1)
dev3d

array([ 2.77099889e-03, -2.80932866e-05, -7.57608277e-05])

In [23]:
xyzt.shape

(3,)

In [13]:
nx, ny = mmt.artefact.nballs
ball_range = np.arange(nx * ny)
x = (ball_range) % nx * mmt.artefact.ball_spacing
y = (ball_range) // nx * mmt.artefact.ball_spacing
z = (ball_range) * 0.0
xyz = np.stack((x, y, z))
mmt.cmm_nominal = mmt.transform3d.map(xyz).T
mmt.cmm_nominal.shape, mmt.cmm_nominal

((25, 3),
 array([[  0.,   0.,   0.],
        [133.,   0.,   0.],
        [266.,   0.,   0.],
        [399.,   0.,   0.],
        [532.,   0.,   0.],
        [  0., 133.,   0.],
        [133., 133.,   0.],
        [266., 133.,   0.],
        [399., 133.,   0.],
        [532., 133.,   0.],
        [  0., 266.,   0.],
        [133., 266.,   0.],
        [266., 266.,   0.],
        [399., 266.,   0.],
        [532., 266.,   0.],
        [  0., 399.,   0.],
        [133., 399.,   0.],
        [266., 399.,   0.],
        [399., 399.,   0.],
        [532., 399.,   0.],
        [  0., 532.,   0.],
        [133., 532.,   0.],
        [266., 532.,   0.],
        [399., 532.,   0.],
        [532., 532.,   0.]]))

In [14]:
np.apply_along_axis(design.linear_model_point, 1, mmt.cmm_nominal, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1 )

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.76890000e-03,  8.84461763e-05, -2.72414223e-04],
       [ 3.53780000e-03,  3.53784705e-04, -1.08965689e-03],
       [ 5.30670000e-03,  7.96015587e-04, -2.45172801e-03],
       [ 7.07560000e-03,  1.41513882e-03, -4.35862757e-03],
       [-1.48960000e-03, -6.76970000e-04,  0.00000000e+00],
       [ 1.90855450e-04, -5.88524814e-04, -1.39921236e-04],
       [ 1.87131090e-03, -3.23187276e-04, -8.24670919e-04],
       [ 3.55176635e-03,  1.19042615e-04, -2.05424905e-03],
       [ 5.23222180e-03,  7.38164859e-04, -3.82865562e-03],
       [-2.97920000e-03, -1.35394000e-03,  0.00000000e+00],
       [-1.38718910e-03, -1.26549580e-03, -7.42824982e-06],
       [ 2.04821801e-04, -1.00015926e-03, -5.59684946e-04],
       [ 1.79683270e-03, -5.57930357e-04, -1.65677009e-03],
       [ 3.38884360e-03,  6.11908964e-05, -3.29868368e-03],
       [-4.46880000e-03, -2.03091000e-03,  0.00000000e+00],
       [-2.96523365e-03, -1.94246680e-03

In [20]:
design.linear_model_matrix(mmt.cmm_nominal, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1,)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.55078000e-03,  2.01363176e-04, -2.93454823e-04],
       [ 3.10156000e-03,  5.79618705e-04, -1.13173809e-03],
       [ 4.65234000e-03,  1.13476659e-03, -2.51484981e-03],
       [ 6.20312000e-03,  1.86680682e-03, -4.44278997e-03],
       [-1.35766404e-03, -6.79629600e-04,  2.58554526e-05],
       [ 1.04671464e-04, -4.78267352e-04, -1.35106657e-04],
       [ 1.56700697e-03, -1.00012752e-04, -8.40897212e-04],
       [ 3.02934247e-03,  4.55134201e-04, -2.09151621e-03],
       [ 4.49167798e-03,  1.18717351e-03, -3.88696366e-03],
       [-2.71532817e-03, -1.35925840e-03,  5.17114102e-05],
       [-1.34143716e-03, -1.15789708e-03,  2.32420146e-05],
       [ 3.24538540e-05, -7.79643409e-04, -5.50055827e-04],
       [ 1.40634486e-03, -2.24497385e-04, -1.66818211e-03],
       [ 2.78023587e-03,  5.07540992e-04, -3.33113685e-03],
       [-4.07299237e-03, -2.03888640e-03,  7.75678729e-05],
       [-2.78754586e-03, -1.83752601e-03

In [16]:
xyzt = (20,20,-100)
design.linear_model_matrix(mmt.cmm_nominal, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1,)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.55078000e-03,  2.01363176e-04, -2.93454823e-04],
       [ 3.10156000e-03,  5.79618705e-04, -1.13173809e-03],
       [ 4.65234000e-03,  1.13476659e-03, -2.51484981e-03],
       [ 6.20312000e-03,  1.86680682e-03, -4.44278997e-03],
       [-1.35766404e-03, -6.79629600e-04,  2.58554526e-05],
       [ 1.04671464e-04, -4.78267352e-04, -1.35106657e-04],
       [ 1.56700697e-03, -1.00012752e-04, -8.40897212e-04],
       [ 3.02934247e-03,  4.55134201e-04, -2.09151621e-03],
       [ 4.49167798e-03,  1.18717351e-03, -3.88696366e-03],
       [-2.71532817e-03, -1.35925840e-03,  5.17114102e-05],
       [-1.34143716e-03, -1.15789708e-03,  2.32420146e-05],
       [ 3.24538540e-05, -7.79643409e-04, -5.50055827e-04],
       [ 1.40634486e-03, -2.24497385e-04, -1.66818211e-03],
       [ 2.78023587e-03,  5.07540992e-04, -3.33113685e-03],
       [-4.07299237e-03, -2.03888640e-03,  7.75678729e-05],
       [-2.78754586e-03, -1.83752601e-03

In [19]:
xyzt = (20,20,-100)
design.linear_model_matrix(mmt.cmm_nominal, xyzt=xyzt, model_params=dc.model_parameters_test, fixed_table=False, bridge_axis=1,)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.55078000e-03,  2.01363176e-04, -2.93454823e-04],
       [ 3.10156000e-03,  5.79618705e-04, -1.13173809e-03],
       [ 4.65234000e-03,  1.13476659e-03, -2.51484981e-03],
       [ 6.20312000e-03,  1.86680682e-03, -4.44278997e-03],
       [-1.35766404e-03, -6.79629600e-04,  2.58554526e-05],
       [ 1.04671464e-04, -4.78267352e-04, -1.35106657e-04],
       [ 1.56700697e-03, -1.00012752e-04, -8.40897212e-04],
       [ 3.02934247e-03,  4.55134201e-04, -2.09151621e-03],
       [ 4.49167798e-03,  1.18717351e-03, -3.88696366e-03],
       [-2.71532817e-03, -1.35925840e-03,  5.17114102e-05],
       [-1.34143716e-03, -1.15789708e-03,  2.32420146e-05],
       [ 3.24538540e-05, -7.79643409e-04, -5.50055827e-04],
       [ 1.40634486e-03, -2.24497385e-04, -1.66818211e-03],
       [ 2.78023587e-03,  5.07540992e-04, -3.33113685e-03],
       [-4.07299237e-03, -2.03888640e-03,  7.75678729e-05],
       [-2.78754586e-03, -1.83752601e-03