Calculate deformation etc without gui interface

In [1]:
import numpy as np

import pyqtgraph as pg
import pyqtgraph.Qt.QtGui as qtg
from cmm_error_map import data_cmpts as dc
from cmm_error_map import design_linear as design
import cmm_error_map.config.config as cf

In [38]:
cmm = dc.pmm_866
p0 = dc.Probe(title="P0", name="p0", length=np.array([0,0,0]))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=cf.artefact_models['Step Gauge 0600'],
    transform_mat=np.identity(4),
    probe=p0,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,
)
model_params = dc.model_parameters_test.copy()
mmt.recalculate(model_params, cmm.cmm_model)

In [39]:
mmt.mmt_nominal.shape

(3, 31)

In [40]:
mmt.cmm_nominal

array([[  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.,
        220., 240., 260., 280., 300., 320., 340., 360., 380., 400., 420.,
        440., 460., 480., 500., 520., 540., 560., 580., 600.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [41]:
mmt.cmm_dev

array([[ 0.00000000e+00,  2.66000000e-04,  5.32000000e-04,
         7.98000000e-04,  1.06400000e-03,  1.33000000e-03,
         1.59600000e-03,  1.86200000e-03,  2.12800000e-03,
         2.39400000e-03,  2.66000000e-03,  2.92600000e-03,
         3.19200000e-03,  3.45800000e-03,  3.72400000e-03,
         3.99000000e-03,  4.25600000e-03,  4.52200000e-03,
         4.78800000e-03,  5.05400000e-03,  5.32000000e-03,
         5.58600000e-03,  5.85200000e-03,  6.11800000e-03,
         6.38400000e-03,  6.65000000e-03,  6.91600000e-03,
         7.18200000e-03,  7.44800000e-03,  7.71400000e-03,
         7.98000000e-03],
       [ 0.00000000e+00,  2.00002660e-06,  8.00010640e-06,
         1.80002394e-05,  3.20004256e-05,  5.00006650e-05,
         7.20009576e-05,  9.80013034e-05,  1.28001702e-04,
         1.62002155e-04,  2.00002660e-04,  2.42003219e-04,
         2.88003830e-04,  3.38004495e-04,  3.92005214e-04,
         4.50005985e-04,  5.12006810e-04,  5.78007687e-04,
         6.48008618e-04,  7.22

In [42]:
mmt.mmt_nominal

array([[  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.,
        220., 240., 260., 280., 300., 320., 340., 360., 380., 400., 420.,
        440., 460., 480., 500., 520., 540., 560., 580., 600.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [43]:
mmt.mmt_dev

array([[ 0.00000000e+00,  2.65999293e-04,  5.31998700e-04,
         7.97998221e-04,  1.06399786e-03,  1.32999760e-03,
         1.59599747e-03,  1.86199744e-03,  2.12799753e-03,
         2.39399774e-03,  2.65999805e-03,  2.92599849e-03,
         3.19199903e-03,  3.45799969e-03,  3.72400046e-03,
         3.99000135e-03,  4.25600235e-03,  4.52200347e-03,
         4.78800469e-03,  5.05400604e-03,  5.32000749e-03,
         5.58600906e-03,  5.85201075e-03,  6.11801254e-03,
         6.38401445e-03,  6.65001648e-03,  6.91601862e-03,
         7.18202087e-03,  7.44802324e-03,  7.71402572e-03,
         7.98002831e-03],
       [ 0.00000000e+00, -5.80007714e-05, -1.12001490e-04,
        -1.62002155e-04, -2.08002766e-04, -2.50003325e-04,
        -2.88003830e-04, -3.22004283e-04, -3.52004682e-04,
        -3.78005027e-04, -4.00005320e-04, -4.18005559e-04,
        -4.32005746e-04, -4.42005879e-04, -4.48005958e-04,
        -4.50005985e-04, -4.48005958e-04, -4.42005879e-04,
        -4.32005746e-04, -4.18

In [44]:
x = mmt.mmt_nominal[0, :]
y = mmt.mmt_dev[0, :]

In [46]:
# 2, n for setData
xy = np.stack((x,y))
xy.shape

(2, 31)