Calculate deformation etc without gui interface

In [20]:
import numpy as np

import pyqtgraph as pg
import pyqtgraph.Qt.QtGui as qtg
from cmm_error_map import data_cmpts as dc
from cmm_error_map import design_linear as design

In [17]:
p0 = dc.Probe(title="P0", name="p0", length=qtg.QVector3D(0, 0, 0))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=dc.default_artefacts["KOBA 0620"],
    transform3d=pg.Transform3D(),
    probe=p0,
    xy2d=None,
    dev2d=None,
    xyz3d=None,
    dev3d=None,
)
mmt.artefact.nballs = (5, 5)
model_params = dc.model_parameters_dict.copy()
mmt.recalculate(model_params)

In [18]:
mmt.xyz3d.shape

(25, 3)

In [19]:
mmt.xyz3d * [-1, 1, 1]

array([[  -0.,    0.,    0.],
       [-133.,    0.,    0.],
       [-266.,    0.,    0.],
       [-399.,    0.,    0.],
       [-532.,    0.,    0.],
       [  -0.,  133.,    0.],
       [-133.,  133.,    0.],
       [-266.,  133.,    0.],
       [-399.,  133.,    0.],
       [-532.,  133.,    0.],
       [  -0.,  266.,    0.],
       [-133.,  266.,    0.],
       [-266.,  266.,    0.],
       [-399.,  266.,    0.],
       [-532.,  266.,    0.],
       [  -0.,  399.,    0.],
       [-133.,  399.,    0.],
       [-266.,  399.,    0.],
       [-399.,  399.,    0.],
       [-532.,  399.,    0.],
       [  -0.,  532.,    0.],
       [-133.,  532.,    0.],
       [-266.,  532.,    0.],
       [-399.,  532.,    0.],
       [-532.,  532.,    0.]])

In [13]:
mmt.xy2d.shape

(25, 2)

In [11]:
box = dc.BoxGrid(
    title='test',
    name='test',
    spacing=(200,200,200),
    npts=(5,4,4),
    probe=p0,
    xyz3d=None,
    dev3d=None,
)
box.recalculate(model_params)

In [12]:
box.xyz3d.shape

(80, 3)

In [23]:
design.linear_dependency(np.array([1,1,1]), model_params)

{'Txx': 0.0,
 'Txy': 0.0,
 'Txz': 0.0,
 'Tyx': 0.0,
 'Tyy': 0.0,
 'Tyz': 0.0,
 'Tzx': 0.0,
 'Tzy': 0.0,
 'Tzz': 0.0,
 'Rxx': 0.0,
 'Rxy': 0.0,
 'Rxz': 0.0,
 'Ryx': 0.0,
 'Ryy': 0.0,
 'Ryz': 0.0,
 'Rzx': 0.0,
 'Rzy': 0.0,
 'Rzz': 0.0,
 'Wxy': 0.0,
 'Wxz': 0.0,
 'Wyz': 0.0}

In [47]:
xyzt = np.array([0.,0., 0.0])
dev3d = design.linear_model_point(np.array([100.,100.,100.]), xyzt, model_params, fixed_table=False, bridge_axis=1)
dev3d

array([0., 0., 0.])

In [48]:
np.apply_along_axis(design.linear_model_point, 1, mmt.xyz3d, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1 )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
design.linear_model_matrix(mmt.xyz3d, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1,)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
xyzt = (20,20,-100)
design.linear_model_matrix(mmt.xyz3d, xyzt=xyzt, model_params=model_params, fixed_table=False, bridge_axis=1,)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
xyzt = (20,20,-100)
design.linear_model_matrix(mmt.xyz3d, xyzt=xyzt, model_params=dc.model_parameters_test, fixed_table=False, bridge_axis=1,)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.55078000e-03,  2.01363176e-04, -2.93454823e-04],
       [ 3.10156000e-03,  5.79618705e-04, -1.13173809e-03],
       [ 4.65234000e-03,  1.13476659e-03, -2.51484981e-03],
       [ 6.20312000e-03,  1.86680682e-03, -4.44278997e-03],
       [-1.35766404e-03, -6.79629600e-04,  2.58554526e-05],
       [ 1.04671464e-04, -4.78267352e-04, -1.35106657e-04],
       [ 1.56700697e-03, -1.00012752e-04, -8.40897212e-04],
       [ 3.02934247e-03,  4.55134201e-04, -2.09151621e-03],
       [ 4.49167798e-03,  1.18717351e-03, -3.88696366e-03],
       [-2.71532817e-03, -1.35925840e-03,  5.17114102e-05],
       [-1.34143716e-03, -1.15789708e-03,  2.32420146e-05],
       [ 3.24538540e-05, -7.79643409e-04, -5.50055827e-04],
       [ 1.40634486e-03, -2.24497385e-04, -1.66818211e-03],
       [ 2.78023587e-03,  5.07540992e-04, -3.33113685e-03],
       [-4.07299237e-03, -2.03888640e-03,  7.75678729e-05],
       [-2.78754586e-03, -1.83752601e-03