working on new code for `Measurement.recalculate`
using numpy for transform math

In [2]:
import numpy as np

import pyqtgraph as pg
from cmm_error_map import data_cmpts as dc
from cmm_error_map import design_linear as design
from cmm_error_map import  gui_cmpts as gc

import matplotlib.pyplot as plt

In [49]:
p0 = dc.Probe(title="P0", name="p0", length=np.array([0, 0, 0]))
cmm = dc.pmm_866
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=dc.default_artefacts["KOBA 0620"],
    transform_mat=np.identity(4),
    probe=p0,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,

)
model_params = dc.model_parameters_dict.copy()
mmt.transform_mat = gc.vec_to_transform3d([10,10,10], (45, 10, 90)).matrix()
mmt.transform_mat


array([[ 0.        , -0.70710677,  0.70710677, 10.        ],
       [ 0.98480773,  0.1227878 ,  0.1227878 , 10.        ],
       [-0.17364818,  0.69636422,  0.69636422, 10.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [50]:
mmt.recalculate(model_params, cmm.cmm_model)

In [51]:
mmt.cmm_nominal

array([[  10.        ,   10.        ,   10.        ,   10.        ,
          10.        ,  -84.04520029,  -84.04520029,  -84.04520029,
         -84.04520029,  -84.04520029, -178.09040058, -178.09040058,
        -178.09040058, -178.09040058, -178.09040058, -272.13560086,
        -272.13560086, -272.13560086, -272.13560086, -272.13560086,
        -366.18080115, -366.18080115, -366.18080115, -366.18080115,
        -366.18080115],
       [  10.        ,  140.97942805,  271.95885611,  402.93828416,
         533.91771221,   26.33077785,  157.31020591,  288.28963396,
         419.26906201,  550.24849007,   42.66155571,  173.64098376,
         304.62041181,  435.59983987,  566.57926792,   58.99233356,
         189.97176161,  320.95118967,  451.93061772,  582.91004577,
          75.32311141,  206.30253947,  337.28196752,  468.26139557,
         599.24082363],
       [  10.        ,  -13.09520775,  -36.1904155 ,  -59.28562325,
         -82.380831  ,  102.61644179,   79.52123404,   56.42602628,


In [52]:
mmt.cmm_dev

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
mmt.mmt_nominal

array([[  0., 133., 266., 399., 532.,   0., 133., 266., 399., 532.,   0.,
        133., 266., 399., 532.,   0., 133., 266., 399., 532.,   0., 133.,
        266., 399., 532.],
       [  0.,   0.,   0.,   0.,   0., 133., 133., 133., 133., 133., 266.,
        266., 266., 266., 266., 399., 399., 399., 399., 399., 532., 532.,
        532., 532., 532.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.]])

In [54]:
mmt.mmt_dev

array([[-3.55271368e-15, -3.02963204e-06, -6.05926414e-06,
        -9.08889621e-06, -1.21185283e-05,  0.00000000e+00,
        -3.02963204e-06, -6.05926414e-06, -9.08889621e-06,
        -1.21185283e-05,  5.32907052e-15, -3.02963204e-06,
        -6.05926419e-06, -9.08889621e-06, -1.21185283e-05,
         1.06581410e-14, -3.02963204e-06, -6.05926414e-06,
        -9.08889621e-06, -1.21185283e-05,  8.88178420e-15,
        -3.02963204e-06, -6.05926414e-06, -9.08889615e-06,
        -1.21185283e-05],
       [ 1.33226763e-15,  3.77475828e-15,  3.33066907e-15,
         6.66133815e-15,  6.21724894e-15, -2.66268214e-06,
        -2.66268214e-06, -2.66268214e-06, -2.66268214e-06,
        -2.66268214e-06, -5.32536427e-06, -5.32536427e-06,
        -5.32536427e-06, -5.32536427e-06, -5.32536427e-06,
        -7.98804643e-06, -7.98804643e-06, -7.98804643e-06,
        -7.98804643e-06, -7.98804638e-06, -1.06507285e-05,
        -1.06507285e-05, -1.06507285e-05, -1.06507285e-05,
        -1.06507285e-05],
    

In [56]:
spacing = cmm.cmm_model.box_spacing
size = cmm.cmm_model.size
npts = (
    int(size[0] // spacing[0]) + 1,
    int(size[1] // spacing[1]) + 1,
    int(size[2] // spacing[2]) + 1,
)
box = dc.BoxGrid(
    title='test',
    name='test',
    spacing=spacing,
    npts=npts,
    probe=p0,
    grid_nominal=None,
    grid_dev=None,
)


In [59]:
box.recalculate(model_params, cmm.cmm_model)

In [60]:
box.grid_nominal

array([[  0., 200., 400., 600., 800.,   0., 200., 400., 600., 800.,   0.,
        200., 400., 600., 800.,   0., 200., 400., 600., 800.,   0., 200.,
        400., 600., 800.,   0., 200., 400., 600., 800.,   0., 200., 400.,
        600., 800.,   0., 200., 400., 600., 800.,   0., 200., 400., 600.,
        800.,   0., 200., 400., 600., 800.,   0., 200., 400., 600., 800.,
          0., 200., 400., 600., 800.,   0., 200., 400., 600., 800.,   0.,
        200., 400., 600., 800.,   0., 200., 400., 600., 800.,   0., 200.,
        400., 600., 800.],
       [  0.,   0.,   0.,   0.,   0., 200., 200., 200., 200., 200., 400.,
        400., 400., 400., 400., 600., 600., 600., 600., 600.,   0.,   0.,
          0.,   0.,   0., 200., 200., 200., 200., 200., 400., 400., 400.,
        400., 400., 600., 600., 600., 600., 600.,   0.,   0.,   0.,   0.,
          0., 200., 200., 200., 200., 200., 400., 400., 400., 400., 400.,
        600., 600., 600., 600., 600.,   0.,   0.,   0.,   0.,   0., 200.,
        200

In [61]:
box.grid_dev

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.