Comparing transform matrix implementations
between blender mathutile, pyqtgraph scipy.spatial.transform and 
https://learnopencv.com/rotation-matrix-to-euler-angles/

In [3]:
import math
import numpy as np
import mathutils as mu
import scipy.spatial.transform as st
import cmm_error_map.gui_cmpts as gc

In [4]:
vloc = [100, 20, 30]
vrot_deg = [-10 , 20, -30] # degrees
vrot_rad = [math.radians(x) for x in vrot_deg]
vrot_rad

[-0.17453292519943295, 0.3490658503988659, -0.5235987755982988]

In [6]:
# blender mathutils
eul_mu = mu.Euler(vrot_rad)
mat_rot = eul_mu.to_matrix()
mat_rot

Matrix(((0.813797652721405, 0.4409696161746979, 0.3785223066806793),
        (-0.46984633803367615, 0.882564127445221, -0.018028317019343376),
        (-0.3420201241970062, -0.16317591071128845, 0.9254165887832642)))

In [7]:
mu_mat = np.array(mat_rot)
mu_mat

array([[ 0.81379765,  0.44096962,  0.37852231],
       [-0.46984634,  0.88256413, -0.01802832],
       [-0.34202012, -0.16317591,  0.92541659]])

In [8]:
# scipy.spatial.transform
rot_st = st.Rotation.from_euler('ZYX', np.flip(vrot_rad))
st_mat = rot_st.as_matrix()
st_mat

array([[ 0.81379768,  0.44096961,  0.37852231],
       [-0.46984631,  0.88256412, -0.01802831],
       [-0.34202014, -0.16317591,  0.92541658]])

In [9]:
np.testing.assert_allclose(st_mat, mu_mat, rtol=1e-5)

In [14]:
loc = np.array(vloc).reshape((-1,1))
mat = np.hstack((st_mat,loc))
mat = np.vstack((mat, np.array([[0,0,0,1]])))
mat


array([[ 8.13797681e-01,  4.40969611e-01,  3.78522306e-01,
         1.00000000e+02],
       [-4.69846310e-01,  8.82564119e-01, -1.80283112e-02,
         2.00000000e+01],
       [-3.42020143e-01, -1.63175911e-01,  9.25416578e-01,
         3.00000000e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [11]:
# scipy.spatial.transform from matrix to euler
rot_st = st.Rotation.from_matrix(st_mat)
rot_st.as_euler('ZYX')

array([-0.52359878,  0.34906585, -0.17453293])

In [12]:
# scipy.spatial.transform using degrees
rot_st = st.Rotation.from_euler('ZYX', np.flip(vrot_deg), degrees=True)
mat_st = rot_st.as_matrix()
mat_st

array([[ 0.81379768,  0.44096961,  0.37852231],
       [-0.46984631,  0.88256412, -0.01802831],
       [-0.34202014, -0.16317591,  0.92541658]])

In [13]:
rot_st = st.Rotation.from_matrix(mat_st)
eul_st = rot_st.as_euler('ZYX', degrees= True)
eul_st = np.flip(eul_st)
eul_st

array([-10.,  20., -30.])

In [15]:
mat[:3, 3]

array([100.,  20.,  30.])

In [17]:
gc.matrix_to_vectors(mat)

(array([100.,  20.,  30.]), array([-10.,  20., -30.]))