In [1]:
import numpy as np
import pickle

In [ ]:
# recode pickle line endings
pfname = "../src/cmm_error_map/mpl_2014/data/ballplate_tmp_data_02.pickle"
data = open(pfname).read().replace("\r\n", "\n")
dst = pfname + ".tmp"
open(dst, "w").write(data)
(d, dtstime, info, dT, c, dE, dM, bm_linear, mmtinfo) = pickle.load(
    open(dst, "rb"), encoding="latin1"
)


In [ ]:
d

In [ ]:
from cmm_error_map import design_matrix_linear_fixed as design

In [ ]:
design.modelparameters

In [ ]:
modeldict = {p[0]: p for p in design.modelparameters}
modeldict

In [ ]:
from dataclasses import dataclass, asdict


@dataclass
class ModelParameters:
    TxxL: float = 0.0
    TxyL: float = 0.0
    TxzL: float = 0.0
    TyxL: float = 0.0
    TyyL: float = 0.0
    TyzL: float = 0.0
    TzxL: float = 0.0
    TzyL: float = 0.0
    TzzL: float = 0.0
    RxxL: float = 0.0
    RxyL: float = 0.0
    RxzL: float = 0.0
    RyxL: float = 0.0
    RyyL: float = 0.0
    RyzL: float = 0.0
    RzxL: float = 0.0
    RzyL: float = 0.0
    RzzL: float = 0.0
    Wxy: float = 0.0
    Wxz: float = 0.0
    Wyz: float = 0.0

In [ ]:
params = ModelParameters()
params

In [ ]:
p = list(asdict(params).values())
type(p), p

In [ ]:
params.TxxL

In [ ]:
params["TxxL"]

In [ ]:
asdict(params)["TxxL"]

In [ ]:
d = asdict(params)
d

In [ ]:
d.TxxL

In [ ]:
import cmm_error_map.design_matrix_linear_fixed as design

In [ ]:
design.model_parameters_dict

In [ ]:
list(design.model_parameters_dict.values())

In [ ]:
i = 5
f"abc {i:02d}"

In [ ]:
start = -5.0
stop = 5.0
step = 0.1
span = np.arange(start, stop + step, step)

In [ ]:
v = 2
int(np.argmin(np.abs(span - v)))

In [ ]:
np.argmin(np.abs(span - v))


In [ ]:
dn = {
    "a": {"value": 0.0, "slide_factor": 1e-8},
    "b": {"value": 0.0, "slide_factor": 1e-8},
    "c": {"value": 0.0, "slide_factor": 1e-8},
    "d": {"value": 0.0, "slide_factor": 1e-5},
}

In [ ]:
[d["slide_factor"] for d in dn.values()]

In [ ]:
span = np.arange(1, 4.1, 0.25)
span

In [ ]:
10**span

In [ ]:
x = np.array([1, 2, 5, 7.5])
np.hstack((x, x * 10, x * 100, x * 1000, [10000]))

In [ ]:
x = "Txx"
y = "sld_" + x
y[:3]

In [ ]:
model_parameters_dict = {
    "Txx": 0.0,
    "Txy": 0.0,
    "Txz": 0.0,
    "Tyx": 0.0,
    "Tyy": 0.0,
    "Tyz": 0.0,
    "Tzx": 0.0,
    "Tzy": 0.0,
    "Tzz": 0.0,
    "Rxx": 0.0,
    "Rxy": 0.0,
    "Rxz": 0.0,
    "Ryx": 0.0,
    "Ryy": 0.0,
    "Ryz": 0.0,
    "Rzx": 0.0,
    "Rzy": 0.0,
    "Rzz": 0.0,
    "Wxy": 0.0,
    "Wxz": 0.0,
    "Wyz": 0.0,
}

In [ ]:
params = np.zeros(21)
params[0] = 1.33e-05
params[3] = -1.12e-05
params[4] = -5.09e-06
params[6] = 2.6e-05
params[7] = 4.6e-06
params[8] = 3.34e-08
params[9] = 7.49e-09
params[10] = 1.54e-08
params[11] = 5e-09
params[12] = -4.58e-09
params[13] = -1.43e-08
params[14] = 2.19e-08
params[15] = 2.49e-09
params[16] = -7.94e-10
params[17] = 4.78e-08


In [ ]:
d = {key: value for key, value in zip(model_parameters_dict.keys(), params)}
d

In [ ]:
x = np.array([1.,2.,3.])
type(x)

In [ ]:
np.linalg.norm(x)

In [ ]:
xn = x/np.linalg.norm(x)
xn

In [ ]:
np.linalg.norm(xn)

In [ ]:
y = np.array([4,5,6])
z = np.array([7,8,9])
t = np.array([0,1,2])

In [ ]:
m1 = np.vstack((x,y,z,t)).T
m1

In [ ]:
np.vstack((m1, [0,0,0,1]))

In [ ]:
import mathutils as mu

In [ ]:
mu.Vector()

In [ ]:
mu.Matrix()

In [ ]:
# data classes with mutable list
from dataclasses import dataclass, field
@dataclass
class SomeClass:
    some_list: list = field(default_factory=list[str])

In [ ]:
d1 = SomeClass(some_list=['a','b','c'])
d2 = SomeClass(some_list=['1','2','3'])

In [ ]:
d1.some_list

In [ ]:
d2.some_list

In [ ]:
d1.some_list.append('d')
d1

In [ ]:
d2

In [ ]:
d3=SomeClass()
d3

In [ ]:
d3.some_list

In [ ]:
my_dict = {}
my_dict["a1"] = my_dict.get("a1", SomeClass())

In [ ]:
my_dict

In [ ]:
my_dict["a1"] = d1
my_dict["a1"] = my_dict.get("a1", SomeClass())
my_dict


In [ ]:
my_dict["b2"] = my_dict.get("b2", SomeClass())
my_dict

In [ ]:
x0 , x1, x2  = 1, 2, 0
z0 , z1, z2  = 0, 0, 1
p0,p1,p2 = 10, 20, 30

In [ ]:

x = mu.Vector((x0,x1,x2)).normalized()
x

In [ ]:
z = mu.Vector((z0,z1,z2)).normalized()
z

In [ ]:
y = x.cross(z)
y

In [ ]:
p = mu.Vector((p0,p1,p2))
p

In [ ]:
mat = mu.Matrix([x,y,z])
mat, mat.transposed()

In [ ]:
mat.is_orthogonal_axis_vectors

In [ ]:
mat4 = mu.Matrix.LocRotScale(p,mat, None)
mat4

In [ ]:
np.array(mat4)

In [ ]:
xt, yt, zt = p
xt

In [ ]:
np.deg2rad(1)

In [ ]:
180 * np.deg2rad(1)

In [ ]:
pd = {}
pd.values()

In [ ]:
for p in pd.values():
    print('hello')

In [ ]:
d = {'a':1}
if 'b' in d:
    print("here I am")

In [ ]:
532/4

In [ ]:
332/4

In [ ]:
nballs = (3,3)
ballspacing = 1.0

ball_count = nballs[0] * nballs[1]
ballnumber = np.arange(ball_count)

xp = (ballnumber % nballs[0]) * ballspacing
yp = (ballnumber // nballs[1]) * ballspacing


In [ ]:
xp, yp

In [ ]:
yp

In [ ]:
xyz1 = np.stack((xp,yp,np.zeros_like(xp), np.ones_like(xp)))
xyz1.shape

In [ ]:
import mathutils as mu
import math

In [ ]:
mat_rot = mu.Matrix.Rotation(math.radians(90.0), 4, 'Z')
mat_rot

In [ ]:
pts = np.array(mat_rot) @ xyz1
pts.shape


In [ ]:
pts

In [ ]:
xyz1

In [ ]:
pts[:,2]

In [ ]:
# check pyqt QTransform against Blender mathutils

In [ ]:
bl_eul =mu.Euler(mu.Vector((1,1,1))).to_matrix()
bl_eul

In [ ]:
from PySide6.QtGui import QMatrix4x4, QQuaternion, QVector3D, QTransform


In [ ]:
mat = QMatrix4x4()
mat

In [ ]:
q1 = QQuaternion().fromEulerAngles(0,0,1.5)
q1

In [ ]:
q1.toRotationMatrix()

In [ ]:
import mathutils as mu
import math

In [ ]:
e1_rad = [0.0,0.0,np.pi/2]
e1_deg = np.rad2deg(e1_rad)


In [ ]:
mu.Euler(e1_rad).to_matrix()

In [ ]:
QQuaternion.fromEulerAngles(e1_deg[2], e1_deg[0], e1_deg[1]).toRotationMatrix()

In [ ]:
mu.Euler( [0, 0, np.deg2rad(90)]).to_matrix()

In [ ]:
mu.Euler( [np.deg2rad(10), np.deg2rad(20), np.deg2rad(30)]).to_matrix()

In [ ]:
from pyqtgraph import Transform3D

In [ ]:
tr = Transform3D()
tr.setToIdentity()
tr.rotate(10, 1, 0, 0)
tr.rotate(20, 0, 1, 0)
tr.rotate(30, 0, 0, 1)
tr.translate(0,0,0)
tr.matrix()

In [ ]:
v1 = QVector3D()

In [ ]:
x,y,z = v1.x(), v1.y(), v1.z() 

In [ ]:
y

In [ ]:
QVector3D(1,2,3)

In [ ]:
for i in range(11):
    print(f"{i:02d}")

In [ ]:

d1 = {"A": "a1", "B": "b1", "C": "c1"}
c1 = ["A", "C"]
n1 = [d1[c] for c in c1]
n1

In [ ]:
from cmm_error_map import data_cmpts as dc

In [ ]:
artefact = dc.default_artefacts["KOBA 0620"]

In [ ]:
ballnumber = np.arange(artefact.nballs[0]* artefact.nballs[1])
x = (ballnumber) % artefact.nballs[0] * artefact.ball_spacing
y = (ballnumber) // artefact.nballs[1] * artefact.ball_spacing
z = (ballnumber) * 0.0
x,y,z

In [ ]:
xyz = np.stack((x,y,z))
xyz.shape, xyz


In [ ]:
xyz[0,:]

In [ ]:
import cmm_error_map.design_matrix_linear_fixed as design

In [ ]:
model_params = design.model_parameters_dict.copy()
pars  = list(model_params.values())
E = design.model_linear(x, y, z, pars, 0., 0., 0.)

In [ ]:
E

In [ ]:
np.stack(E) + xyz

In [ ]:
size = (1, 2, 3)
x,y,z = size
z

In [2]:
from cmm_error_map import data_cmpts as dc
from cmm_error_map import gui_cmpts as gc
from cmm_error_map import design_matrix_linear_fixed as design

import pyqtgraph as pg
import pyqtgraph.Qt.QtGui as qtg

In [3]:
p0 = dc.Probe(title="P0", name="p0", length=qtg.QVector3D(0, 0, 0))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=dc.default_artefacts["KOBA 0620"],
    transform3d=pg.Transform3D(),
    probe=p0,
    xy2d=None,
    dev2d=None,
    xyz3d=None,
    dev3d=None,
)
mmt.artefact.nballs = (5, 4)
model_params = design.model_parameters_dict.copy()
mmt.recalculate(model_params)

In [4]:
pars = list(model_params.values())
vprobe = mmt.probe.length
xt, yt, zt = vprobe.x(), vprobe.y(), vprobe.z()
XYZ, eXYZ = design.machine_deformation(pars, xt, yt, zt)
pXYZ_3D = XYZ + 1.0 * eXYZ

In [ ]:
pXYZ_3D.shape

line pairs for GLLinePlotItem need to be (n*2,3), where n is the number of lines
need index triples such that pXYZ_3D[0,0,0, :], pXYZ[1,0,0, :]  is the first line segment 
```
0 0 0 
1 0 0
1 0 0 
2 0 0 
2 0 0
3 0 0
3 0 0
4 0 0

0 1 0

to create this in 2d see update_plot2d_plate


In [ ]:
# as loops
nx, ny, nz = pXYZ_3D.shape[:3]
inds = []
# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        indx = np.arange(nx)
        indx = np.repeat(indx, 2)[1:-1]
        for i in indx:
            inds.append([i, j, k])

# lines parallel to y-axis          
for k in range(nz):
    for i in range(nx):
        indy = np.arange(ny)
        indy = np.repeat(indy, 2)[1:-1]
        for j in indy:
            inds.append([i, j, k])

# lines parallel to z-axis          
for j in range(ny):
    for i in range(nx):
        indz = np.arange(nz)
        indz = np.repeat(indz, 2)[1:-1]
        for k in indz:
            inds.append([i, j, k])

In [ ]:
inds2 = []
# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = np.arange(nx)
        ind = np.repeat(ind, 2)[1:-1]
        indx = [[i,j,k] for i in ind]
        inds2.extend(indx)

# lines parallel to y-axis          
for k in range(nz):
    for i in range(nx):
        ind = np.arange(ny)
        ind = np.repeat(ind, 2)[1:-1]
        indy = [[i,j,k] for i in ind]
        inds2.extend(indy)

# lines parallel to z-axis          
for j in range(ny):
    for i in range(nx):
        ind = np.arange(nz)
        ind = np.repeat(ind, 2)[1:-1]
        indz = [[i,j,k] for i in ind]
        inds2.extend(indz)
        
len(inds2), len(inds)

In [ ]:
nx, ny, nz = 3, 3, 3
inds3 = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [[i,j,k] for i in indx]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to y-axis          
for k in range(nz):
    for i in range(nx):
        ind = [[i,j,k] for j in indy]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to z-axis          
for j in range(ny):
    for i in range(nx):
        ind = [[i,j,k] for k in indz]
        inds3.extend(ind)

print(len(inds3))

In [ ]:
# this is two points per edge which is correct length

In [77]:
nx, ny, nz = 5, 4, 4
inds3 = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [[i,j,k] for i in indx]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to y-axis          
for k in range(nz):
    for i in range(nx):
        ind = [[i,j,k] for j in indy]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to z-axis          
for j in range(ny):
    for i in range(nx):
        ind = [[i,j,k] for k in indz]
        inds3.extend(ind)

print(len(inds3))

128
248
368


In [58]:
i1 = np.array(gc.grid_line_indicies((5,4,4)))
i1.shape

(368, 3)

In [59]:
pXYZ_3D.shape

(5, 4, 4, 3)

In [12]:
m = np.arange(5*4*4).reshape((5,4,4))
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [25]:
m[1,2,3]

27

In [60]:
i1[319]

array([1, 2, 3])

In [61]:
m[i1[319]]

array([[[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [62]:
m[*i1[319]]

27

In [63]:
pXYZ_3D[1,2,3, :]

array([200., 400., 600.])

In [64]:
pXYZ_3D[*i1[319], :]

array([200., 400., 600.])

In [41]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([0, 1, 2, 2, 1, 0])


In [42]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a[b, :]

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [3, 4],
       [1, 2]])

In [49]:
mxyz = np.stack((m,m,m), axis=3 )
mxyz.shape

(5, 4, 4, 3)

In [65]:
mxyz[i1[:, 0], i1[:, 1], i1[:, 2],  :]

array([[ 0,  0,  0],
       [16, 16, 16],
       [16, 16, 16],
       ...,
       [78, 78, 78],
       [78, 78, 78],
       [79, 79, 79]])

In [66]:
mxyz[1,2, 3, :]

array([27, 27, 27])

In [67]:
mxyz[b, 2, 3, :]

array([[11, 11, 11],
       [27, 27, 27],
       [43, 43, 43],
       [43, 43, 43],
       [27, 27, 27],
       [11, 11, 11]])

In [69]:
i1[1, :]

array([1, 0, 0])

In [70]:
i1[319, :]

array([1, 2, 3])

In [73]:
mxyz[i1[319, 0], i1[319, 1] , i1[319, 2], :]

array([27, 27, 27])

In [75]:
mind = mxyz[i1[:, 0], i1[:, 1] , i1[:, 2], :]
mind.shape

(368, 3)

In [78]:
npts = (5, 4, 4)
pnts_total = np.arange(npts[0] *npts[1] * npts[2])
pnts_total


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [79]:
x = pnts_total % npts[0]
x

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
       4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0,
       1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [81]:
y = pnts_total // npts[0]
y

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13,
       13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15])

In [82]:
z = pnts_total // (npts[0] * npts[1])
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [27]:
xyz, dev  = dc.data_plot3d_box(mmt.probe.length, model_params, npts=(3,3,2), spacing=(1.,1.,1.) )

In [28]:
xyz

array([[0., 0., 0.],
       [1., 0., 0.],
       [2., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [0., 2., 0.],
       [1., 2., 0.],
       [2., 2., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [0., 2., 1.],
       [1., 2., 1.],
       [2., 2., 1.]])

In [48]:
xyz.shape

(18, 3)

0112011201120112

In [45]:
nx, ny, nz = (4,3,3)
indicies = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [i + j*nx + k*nx*ny for i in indx]
        indicies.extend(ind)

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        ind = [i + j*nx + k*nx*ny for j in indy]
        indicies.extend(ind)

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        ind = [i + j*nx + k*nx*ny  for k in indz]
        indicies.extend(ind)
  

In [46]:
len(indicies)

48

In [39]:
indx

array([0, 1, 1, 2, 2, 3])

In [47]:
indicies

[0,
 12,
 12,
 24,
 1,
 13,
 13,
 25,
 2,
 14,
 14,
 26,
 3,
 15,
 15,
 27,
 4,
 16,
 16,
 28,
 5,
 17,
 17,
 29,
 6,
 18,
 18,
 30,
 7,
 19,
 19,
 31,
 8,
 20,
 20,
 32,
 9,
 21,
 21,
 33,
 10,
 22,
 22,
 34,
 11,
 23,
 23,
 35]

In [3]:
int(800.0 // 200.0)

4