In [1]:
import numpy as np
import pickle

In [9]:
import cmm_error_map.config as cf
import cmm_error_map.data_cmpts as dc

In [7]:
text = "0.0, 1.0"
coeffs = text.split(",")
coeffs = [float(c) for c in coeffs]
coeffs

ValueError: could not convert string to float: ''

In [4]:
cf.config_folder

PosixPath('/home/elfnor/gits/ls_cmm_error_map/config')

In [5]:
cf.machines_toml

PosixPath('/home/elfnor/gits/ls_cmm_error_map/config/machines.toml')

In [6]:
1738635857.715278 - 1738635857.682751

0.03252696990966797

In [7]:
1738636148.704041 - 1738636148.637198

0.06684303283691406

In [ ]:
180 * np.deg2rad(1)

In [ ]:
pd = {}
pd.values()

In [ ]:
for p in pd.values():
    print("hello")

In [ ]:
d = {"a": 1}
if "b" in d:
    print("here I am")

In [ ]:
532 / 4

In [ ]:
332 / 4

In [ ]:
nballs = (3, 3)
ballspacing = 1.0

ball_count = nballs[0] * nballs[1]
ballnumber = np.arange(ball_count)

xp = (ballnumber % nballs[0]) * ballspacing
yp = (ballnumber // nballs[1]) * ballspacing


In [ ]:
xp, yp

In [ ]:
yp

In [ ]:
xyz1 = np.stack((xp, yp, np.zeros_like(xp), np.ones_like(xp)))
xyz1.shape

In [ ]:
import mathutils as mu
import math

In [ ]:
mat_rot = mu.Matrix.Rotation(math.radians(90.0), 4, "Z")
mat_rot

In [ ]:
pts = np.array(mat_rot) @ xyz1
pts.shape


In [ ]:
pts

In [ ]:
xyz1

In [ ]:
pts[:, 2]

In [ ]:
# check pyqt QTransform against Blender mathutils

In [ ]:
bl_eul = mu.Euler(mu.Vector((1, 1, 1))).to_matrix()
bl_eul

In [ ]:
from PySide6.QtGui import QMatrix4x4, QQuaternion, QVector3D, QTransform


In [ ]:
mat = QMatrix4x4()
mat

In [ ]:
q1 = QQuaternion().fromEulerAngles(0, 0, 1.5)
q1

In [ ]:
q1.toRotationMatrix()

In [ ]:
import mathutils as mu
import math

In [ ]:
e1_rad = [0.0, 0.0, np.pi / 2]
e1_deg = np.rad2deg(e1_rad)


In [ ]:
mu.Euler(e1_rad).to_matrix()

In [ ]:
QQuaternion.fromEulerAngles(e1_deg[2], e1_deg[0], e1_deg[1]).toRotationMatrix()

In [ ]:
mu.Euler([0, 0, np.deg2rad(90)]).to_matrix()

In [ ]:
mu.Euler([np.deg2rad(10), np.deg2rad(20), np.deg2rad(30)]).to_matrix()

In [ ]:
from pyqtgraph import Transform3D

In [ ]:
tr = Transform3D()
tr.setToIdentity()
tr.rotate(10, 1, 0, 0)
tr.rotate(20, 0, 1, 0)
tr.rotate(30, 0, 0, 1)
tr.translate(0, 0, 0)
tr.matrix()

In [ ]:
v1 = QVector3D()

In [ ]:
x, y, z = v1.x(), v1.y(), v1.z()

In [ ]:
y

In [ ]:
QVector3D(1, 2, 3)

In [ ]:
for i in range(11):
    print(f"{i:02d}")

In [ ]:
d1 = {"A": "a1", "B": "b1", "C": "c1"}
c1 = ["A", "C"]
n1 = [d1[c] for c in c1]
n1

In [ ]:
from cmm_error_map import data_cmpts as dc

In [ ]:
artefact = dc.default_artefacts["KOBA 0620"]

In [ ]:
ballnumber = np.arange(artefact.nballs[0] * artefact.nballs[1])
x = (ballnumber) % artefact.nballs[0] * artefact.ball_spacing
y = (ballnumber) // artefact.nballs[1] * artefact.ball_spacing
z = (ballnumber) * 0.0
x, y, z

In [ ]:
xyz = np.stack((x, y, z))
xyz.shape, xyz


In [ ]:
xyz[0, :]

In [ ]:
import cmm_error_map.design_matrix_linear_fixed as design

In [ ]:
model_params = design.model_parameters_dict.copy()
pars = list(model_params.values())
E = design.model_linear(x, y, z, pars, 0.0, 0.0, 0.0)

In [ ]:
E

In [ ]:
np.stack(E) + xyz

In [ ]:
size = (1, 2, 3)
x, y, z = size
z

In [ ]:
from cmm_error_map import data_cmpts as dc
from cmm_error_map import gui_cmpts as gc
from cmm_error_map import design_matrix_linear_fixed as design

import pyqtgraph as pg
import pyqtgraph.Qt.QtGui as qtg

In [ ]:
p0 = dc.Probe(title="P0", name="p0", length=qtg.QVector3D(0, 0, 0))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=dc.default_artefacts["KOBA 0620"],
    transform3d=pg.Transform3D(),
    probe=p0,
    xy2d=None,
    dev2d=None,
    xyz3d=None,
    dev3d=None,
)
mmt.artefact.nballs = (5, 4)
model_params = design.model_parameters_dict.copy()
mmt.recalculate(model_params)

In [ ]:
pars = list(model_params.values())
vprobe = mmt.probe.length
xt, yt, zt = vprobe.x(), vprobe.y(), vprobe.z()
XYZ, eXYZ = design.machine_deformation(pars, xt, yt, zt)
pXYZ_3D = XYZ + 1.0 * eXYZ

In [ ]:
pXYZ_3D.shape

line pairs for GLLinePlotItem need to be (n*2,3), where n is the number of lines
need index triples such that pXYZ_3D[0,0,0, :], pXYZ[1,0,0, :]  is the first line segment 
```
0 0 0 
1 0 0
1 0 0 
2 0 0 
2 0 0
3 0 0
3 0 0
4 0 0

0 1 0

to create this in 2d see update_plot2d_plate


In [ ]:
# as loops
nx, ny, nz = pXYZ_3D.shape[:3]
inds = []
# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        indx = np.arange(nx)
        indx = np.repeat(indx, 2)[1:-1]
        for i in indx:
            inds.append([i, j, k])

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        indy = np.arange(ny)
        indy = np.repeat(indy, 2)[1:-1]
        for j in indy:
            inds.append([i, j, k])

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        indz = np.arange(nz)
        indz = np.repeat(indz, 2)[1:-1]
        for k in indz:
            inds.append([i, j, k])

In [ ]:
inds2 = []
# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = np.arange(nx)
        ind = np.repeat(ind, 2)[1:-1]
        indx = [[i, j, k] for i in ind]
        inds2.extend(indx)

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        ind = np.arange(ny)
        ind = np.repeat(ind, 2)[1:-1]
        indy = [[i, j, k] for i in ind]
        inds2.extend(indy)

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        ind = np.arange(nz)
        ind = np.repeat(ind, 2)[1:-1]
        indz = [[i, j, k] for i in ind]
        inds2.extend(indz)

len(inds2), len(inds)

In [ ]:
nx, ny, nz = 3, 3, 3
inds3 = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [[i, j, k] for i in indx]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        ind = [[i, j, k] for j in indy]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        ind = [[i, j, k] for k in indz]
        inds3.extend(ind)

print(len(inds3))

In [ ]:
# this is two points per edge which is correct length

In [ ]:
nx, ny, nz = 5, 4, 4
inds3 = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [[i, j, k] for i in indx]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        ind = [[i, j, k] for j in indy]
        inds3.extend(ind)
print(len(inds3))

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        ind = [[i, j, k] for k in indz]
        inds3.extend(ind)

print(len(inds3))

In [ ]:
i1 = np.array(gc.grid_line_indicies((5, 4, 4)))
i1.shape

In [ ]:
pXYZ_3D.shape

In [ ]:
m = np.arange(5 * 4 * 4).reshape((5, 4, 4))
m

In [ ]:
m[1, 2, 3]

In [ ]:
i1[319]

In [ ]:
m[i1[319]]

In [ ]:
m[*i1[319]]

In [ ]:
pXYZ_3D[1, 2, 3, :]

In [ ]:
pXYZ_3D[*i1[319], :]

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([0, 1, 2, 2, 1, 0])


In [ ]:
a

In [ ]:
a[b, :]

In [ ]:
mxyz = np.stack((m, m, m), axis=3)
mxyz.shape

In [ ]:
mxyz[i1[:, 0], i1[:, 1], i1[:, 2], :]

In [ ]:
mxyz[1, 2, 3, :]

In [ ]:
mxyz[b, 2, 3, :]

In [ ]:
i1[1, :]

In [ ]:
i1[319, :]

In [ ]:
mxyz[i1[319, 0], i1[319, 1], i1[319, 2], :]

In [ ]:
mind = mxyz[i1[:, 0], i1[:, 1], i1[:, 2], :]
mind.shape

In [ ]:
npts = (5, 4, 4)
pnts_total = np.arange(npts[0] * npts[1] * npts[2])
pnts_total


In [ ]:
x = pnts_total % npts[0]
x

In [ ]:
y = pnts_total // npts[0]
y

In [ ]:
z = pnts_total // (npts[0] * npts[1])
z

In [ ]:
xyz, dev = dc.data_plot3d_box(
    mmt.probe.length, model_params, npts=(3, 3, 2), spacing=(1.0, 1.0, 1.0)
)

In [ ]:
xyz

In [ ]:
xyz.shape

0112011201120112

In [ ]:
nx, ny, nz = (4, 3, 3)
indicies = []
indx = np.repeat(np.arange(nx), 2)[1:-1]
indy = np.repeat(np.arange(ny), 2)[1:-1]
indz = np.repeat(np.arange(nz), 2)[1:-1]

# lines parallel to x-axis
for k in range(nz):
    for j in range(ny):
        ind = [i + j * nx + k * nx * ny for i in indx]
        indicies.extend(ind)

# lines parallel to y-axis
for k in range(nz):
    for i in range(nx):
        ind = [i + j * nx + k * nx * ny for j in indy]
        indicies.extend(ind)

# lines parallel to z-axis
for j in range(ny):
    for i in range(nx):
        ind = [i + j * nx + k * nx * ny for k in indz]
        indicies.extend(ind)

In [ ]:
len(indicies)

In [ ]:
indx

In [ ]:
indicies

In [ ]:
int(800.0 // 200.0)

In [ ]:
cols = [1, 1, 1, 0.5] * 25
cols = np.array(cols).reshape(-1, 4)
cols

In [ ]:
cols[4, :] = [0.5, 1, 1, 0.5]
cols

In [ ]:
x = 0
int(not x)

In [ ]:
import tomllib as toml
from pathlib import Path
import cmm_error_map.data_cmpts as dc

In [ ]:
def read_toml(fn, input_type):
    with open(fn, "rb") as f:
        toml_in = toml.load(f)
    toml_in = {key: input_type(**value) for key, value in toml_in.items()}
    return toml_in

In [ ]:
fn = Path("/home/elfnor/gits/ls_cmm_error_map/src/cmm_error_map/config/machines.toml")
read_toml(fn, dc.MachineType)

In [19]:
import numpy as np
import cmm_error_map.config.config as cf

cf.artefact_models

{'KOBA 0620': ArtefactType(title='KOBA 0620', nballs=[5, 5], ball_spacing=133.0),
 'KOBA 0420': ArtefactType(title='KOBA 0420', nballs=[5, 5], ball_spacing=83.0),
 'KOBA 0320': ArtefactType(title='KOBA 0320', nballs=[5, 5], ball_spacing=60.0),
 'Step Gauge 0600': ArtefactType(title='Step Gauge 0600', nballs=[61, 1], ball_spacing=10.0)}

In [114]:
artefact = cf.artefact_models["Step Gauge 0600"]

In [31]:
np.cos(np.radians(30))

0.8660254037844387

In [48]:
rot45z = np.array(
    [[0.5, -0.866, 0, 100], [0.866, 0.5, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
)

In [56]:
rot90z = np.array([[0, -1, 0, 100], [1, 0.0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])

In [117]:
cmm = dc.pmm_866
p0 = dc.Probe(title="P0", name="p0", length=np.array([0, 0, 0]))
mmt = dc.Measurement(
    title="m1",
    name="mmt_00",
    artefact=artefact,
    transform_mat=rot45z,
    probe=p0,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,
)
model_params = dc.model_parameters_test.copy()
mmt.recalculate(model_params, cmm.cmm_model)

NameError: name 'rot45z' is not defined

In [64]:
mmt.cmm_nominal

array([[100.  , 105.  , 110.  , 115.  , 120.  , 125.  , 130.  , 135.  ,
        140.  , 145.  , 150.  , 155.  , 160.  , 165.  , 170.  , 175.  ,
        180.  , 185.  , 190.  , 195.  , 200.  , 205.  , 210.  , 215.  ,
        220.  , 225.  , 230.  , 235.  , 240.  , 245.  , 250.  , 255.  ,
        260.  , 265.  , 270.  , 275.  , 280.  , 285.  , 290.  , 295.  ,
        300.  , 305.  , 310.  , 315.  , 320.  , 325.  , 330.  , 335.  ,
        340.  , 345.  , 350.  , 355.  , 360.  , 365.  , 370.  , 375.  ,
        380.  , 385.  , 390.  , 395.  , 400.  ],
       [  0.  ,   8.66,  17.32,  25.98,  34.64,  43.3 ,  51.96,  60.62,
         69.28,  77.94,  86.6 ,  95.26, 103.92, 112.58, 121.24, 129.9 ,
        138.56, 147.22, 155.88, 164.54, 173.2 , 181.86, 190.52, 199.18,
        207.84, 216.5 , 225.16, 233.82, 242.48, 251.14, 259.8 , 268.46,
        277.12, 285.78, 294.44, 303.1 , 311.76, 320.42, 329.08, 337.74,
        346.4 , 355.06, 363.72, 372.38, 381.04, 389.7 , 398.36, 407.02,
        415.68,

In [65]:
xyz0 = mmt.cmm_nominal[:, 0]
xyz0

array([100.,   0.,   0.])

In [66]:
vx = mmt.cmm_nominal[:, -1] - xyz0
vx = vx / np.linalg.norm(vx)
vx

array([0.500011  , 0.86601905, 0.        ])

In [67]:
vy = np.array([0, 1, 0])

In [70]:
 1 - np.dot(vx,vy) 

0.13398094737126087

In [8]:
import pyqtgraph.Qt.QtGui as qtg
import pyqtgraph as pg
import numpy as np

In [4]:
col = pg.mkColor("lightblue")
col

PySide6.QtGui.QColor.fromRgbF(0.678431, 0.847059, 0.901961, 1.000000)

In [11]:
np.array(col.toTuple())

array([173, 216, 230, 255])

In [13]:
np.array(col.getRgbF())

array([0.67843139, 0.84705883, 0.90196079, 1.        ])

In [2]:
from numpy.polynomial import Polynomial as Poly

In [4]:
p123 = Poly([1, 2, 3])
p123

Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1], symbol='x')

In [5]:
p123(10)

321.0

In [2]:
import datetime as dt

In [7]:
dt.datetime.now().isoformat(sep=" ")

'2025-02-19 14:23:58.890420'

In [118]:
ballspacing = 133.0
x0, y0, z0 = 250.0, 50.0, 50.0
transform_mat_xz = dc.matrix_from_vectors(
    [x0, y0 + 2.0 * ballspacing, z0],
    [90.0, 0.0, 0.0],
)
xt_xz, yt_xz, zt_xz = 0.0, 130.0, -243.4852
prb_xz = dc.Probe(title="P0", name="p0", length=np.array([xt_xz, yt_xz, zt_xz]))
mmt = dc.Measurement(
    title="Plate XZ",
    name="mmt_01",
    artefact=cf.artefact_models["KOBA 0620"],
    transform_mat=transform_mat_xz,
    probe=prb_xz,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,
)

In [95]:
mmt1 = mmt

In [96]:
mmt1 == mmt

True

In [97]:
mmt.recalculate(dc.model_parameters_test, dc.pmm_866.cmm_model)

In [98]:
mmt1 == mmt

True

In [99]:
mmt2 = dc.Measurement(
    title="Plate XZ",
    name="mmt_01",
    artefact=cf.artefact_models["KOBA 0620"],
    transform_mat=transform_mat_xz,
    probe=prb_xz,
    cmm_nominal=None,
    cmm_dev=None,
    mmt_nominal=None,
    mmt_dev=None,
)

In [100]:
mmt2 == mmt

False

In [101]:
mmt2.recalculate(dc.model_parameters_test, dc.pmm_866.cmm_model)
mmt2 == mmt

True

In [102]:
mmt2.mmt_dev[1, 1] = 999
mmt2 == mmt

False

In [72]:
mmt2.name = "I'm wrong"
mmt2 == mmt

False

In [103]:
copy(mmt2)

The system cannot find the file specified.


In [31]:
prb1 = dc.Probe(title="P0", name="p0", length=np.array([xt_xz, yt_xz, zt_xz]))

In [32]:
prb2 = dc.Probe(title="P0", name="p0", length=np.array([xt_xz, yt_xz, zt_xz]))

In [33]:
prb1 == prb2

True

In [ ]:
prb3 = dc.Probe(title="P0", name="p0", length=np.array([xt_xz + 1.0, yt_xz, zt_xz]))

In [37]:
prb1 == prb3

False

In [ ]:
a = [False] + [True] * 3
a

[False, True, True, True]

In [61]:
any(a)

True

In [ ]:
from dataclasses import astuple, asdict

t1 = asdict(mmt)

In [45]:
t1

{'title': 'Plate XZ',
 'name': 'mmt_01',
 'artefact': {'title': 'KOBA 0620', 'nballs': [5, 5], 'ball_spacing': 133.0},
 'transform_mat': array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          2.50000000e+02],
        [ 0.00000000e+00,  2.22044605e-16, -1.00000000e+00,
          3.16000000e+02],
        [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16,
          5.00000000e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 'probe': {'title': 'P0',
  'name': 'p0',
  'length': array([   0.    ,  130.    , -243.4852])},
 'cmm_nominal': array([[250., 383., 516., 649., 782., 250., 383., 516., 649., 782., 250.,
         383., 516., 649., 782., 250., 383., 516., 649., 782., 250., 383.,
         516., 649., 782.],
        [316., 316., 316., 316., 316., 316., 316., 316., 316., 316., 316.,
         316., 316., 316., 316., 316., 316., 316., 316., 316., 316., 316.,
         316., 316., 316.],
        [ 50.,  50.,  50.,  50.,  50., 183., 1

In [ ]:
t1["probe"], type(t1["probe"])

({'title': 'P0',
  'name': 'p0',
  'length': array([   0.    ,  130.    , -243.4852])},
 dict)

In [ ]:
import dataclasses

tuple(getattr(prb3, field.name) for field in dataclasses.fields(prb3))

('P0', 'p0', array([   1.    ,  130.    , -243.4852]))

In [49]:
tuple(getattr(mmt, field.name) for field in dataclasses.fields(mmt))

('Plate XZ',
 'mmt_01',
 ArtefactType(title='KOBA 0620', nballs=[5, 5], ball_spacing=133.0),
 array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          2.50000000e+02],
        [ 0.00000000e+00,  2.22044605e-16, -1.00000000e+00,
          3.16000000e+02],
        [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16,
          5.00000000e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 Probe(title='P0', name='p0', length=array([   0.    ,  130.    , -243.4852])),
 array([[250., 383., 516., 649., 782., 250., 383., 516., 649., 782., 250.,
         383., 516., 649., 782., 250., 383., 516., 649., 782., 250., 383.,
         516., 649., 782.],
        [316., 316., 316., 316., 316., 316., 316., 316., 316., 316., 316.,
         316., 316., 316., 316., 316., 316., 316., 316., 316., 316., 316.,
         316., 316., 316.],
        [ 50.,  50.,  50.,  50.,  50., 183., 183., 183., 183., 183., 316.,
         316., 316., 316., 316., 449., 449., 4

In [ ]:
now = "2025-02-19 14:23:58.890420"

In [12]:
header = dc.short_header(mmt, now)

In [13]:
header

'save time,2025-02-19 14:23:58.890420\ntitle,Plate XZ\nartefact.title,KOBA 0620\nartefact.nballs,5,5 \nartefact.ball_spacing,133.0\nlocation,250.0, 316.0, 50.0\nrotation/deg,89.99999999999999, 0.0, 0.0\n'

In [ ]:
header2 = (
    "save time,2025-02-19 14:23:58.890420\n"
    "title,Plate XZ\n"
    "artefact.title,KOBA 0620\n"
    "artefact.nballs,5,5 \n"
    "artefact.ball_spacing,133.0\n"
    "location,250.0, 316.0, 50.0\n"
    "rotation/deg,89.99999999999999, 0.0, 0.0\n"
)

In [18]:
header == header2

True

In [16]:
header2

('save time,2025-02-19 14:23:58.890420\n',
 'title,Plate XZ\n',
 'artefact.title,KOBA 0620\n',
 'artefact.nballs,5,5 \n',
 'artefact.ball_spacing,133.0\n',
 'location,250.0, 316.0, 50.0\n',
 'rotation/deg,89.99999999999999, 0.0, 0.0\n')

In [104]:
import dataclasses

In [ ]:
mmt2 = dataclasses.replace(mmt)

In [107]:
mmt2 == mmt

True

In [108]:
mmt2.probe == mmt.probe

True

In [ ]:
mmt2.name = "I'm wrong"
mmt2 == mmt

False

In [110]:
mmt2 = dataclasses.replace(mmt)
mmt2 == mmt

True

In [111]:
mmt2.probe.name = "wrong"
mmt2 == mmt

True

In [112]:
mmt.probe.name

'wrong'