In [1]:
import numpy as np
import pickle

In [6]:
# recode pickle line endings
pfname = "../src/cmm_error_map/mpl_2014/data/ballplate_tmp_data_02.pickle"
data = open(pfname).read().replace("\r\n", "\n")
dst = pfname + ".tmp"
open(dst, "w").write(data)
(d, dtstime, info, dT, c, dE, dM, bm_linear, mmtinfo) = pickle.load(
    open(dst, "rb"), encoding="latin1"
)


In [7]:
d

array([[ 1.000e+00,  1.000e+00,  1.000e+00, ...,  0.000e+00,  0.000e+00,
         3.500e-04],
       [ 1.000e+00,  1.000e+00,  2.000e+00, ..., -2.600e-04,  2.229e-02,
         7.300e-04],
       [ 1.000e+00,  1.000e+00,  3.000e+00, ..., -5.000e-04,  3.027e-02,
         3.400e-04],
       ...,
       [ 6.000e+00,  6.000e+00,  3.800e+01, ...,  7.000e-04,  1.914e-02,
         4.300e-04],
       [ 6.000e+00,  6.000e+00,  3.900e+01, ...,  5.200e-04,  1.443e-02,
         1.060e-03],
       [ 6.000e+00,  6.000e+00,  4.000e+01, ...,  0.000e+00,  0.000e+00,
         6.600e-04]])

In [1]:
from cmm_error_map import design_matrix_linear_fixed as design

In [2]:
design.modelparameters

[('Txx', 0, 5, (0,), (16,), (1,)),
 ('Txy', 0, 5, (1,), (16,), (-1,)),
 ('Txz', 0, 5, (2,), (16,), (-1,)),
 ('Tyx', 1, 5, (0,), (16,), (-1,)),
 ('Tyy', 1, 5, (1,), (16,), (1,)),
 ('Tyz', 1, 5, (2,), (16,), (-1,)),
 ('Tzx', 2, 4, (0,), (16,), (-1,)),
 ('Tzy', 2, 4, (1,), (16,), (-1,)),
 ('Tzz', 2, 4, (2,), (16,), (1,)),
 ('Rxx', 0, 5, (1, 2), (15, 14), (1, -1)),
 ('Rxy', 0, 5, (0, 2), (15, 13), (-1, 1)),
 ('Rxz', 0, 5, (0, 1), (14, 13), (1, -1)),
 ('Ryx', 1, 5, (1, 2), (15, 11), (1, -1)),
 ('Ryy', 1, 5, (0, 2), (15, 10), (-1, 1)),
 ('Ryz', 1, 5, (0, 1), (11, 10), (1, -1)),
 ('Rzx', 2, 4, (1, 2), (12, 11), (1, -1)),
 ('Rzy', 2, 4, (0, 2), (12, 10), (-1, 1)),
 ('Rzz', 2, 4, (0, 1), (11, 10), (1, -1)),
 ('Wxy', -1, 1, (0, 1), (14, 13), (-1, -1)),
 ('Wxz', -1, 1, (0, 2), (15, 13), (-1, -1)),
 ('Wyz', -1, 1, (1, 2), (15, 14), (-1, -1))]

In [3]:
modeldict = {p[0]: p for p in design.modelparameters}
modeldict

{'Txx': ('Txx', 0, 5, (0,), (16,), (1,)),
 'Txy': ('Txy', 0, 5, (1,), (16,), (-1,)),
 'Txz': ('Txz', 0, 5, (2,), (16,), (-1,)),
 'Tyx': ('Tyx', 1, 5, (0,), (16,), (-1,)),
 'Tyy': ('Tyy', 1, 5, (1,), (16,), (1,)),
 'Tyz': ('Tyz', 1, 5, (2,), (16,), (-1,)),
 'Tzx': ('Tzx', 2, 4, (0,), (16,), (-1,)),
 'Tzy': ('Tzy', 2, 4, (1,), (16,), (-1,)),
 'Tzz': ('Tzz', 2, 4, (2,), (16,), (1,)),
 'Rxx': ('Rxx', 0, 5, (1, 2), (15, 14), (1, -1)),
 'Rxy': ('Rxy', 0, 5, (0, 2), (15, 13), (-1, 1)),
 'Rxz': ('Rxz', 0, 5, (0, 1), (14, 13), (1, -1)),
 'Ryx': ('Ryx', 1, 5, (1, 2), (15, 11), (1, -1)),
 'Ryy': ('Ryy', 1, 5, (0, 2), (15, 10), (-1, 1)),
 'Ryz': ('Ryz', 1, 5, (0, 1), (11, 10), (1, -1)),
 'Rzx': ('Rzx', 2, 4, (1, 2), (12, 11), (1, -1)),
 'Rzy': ('Rzy', 2, 4, (0, 2), (12, 10), (-1, 1)),
 'Rzz': ('Rzz', 2, 4, (0, 1), (11, 10), (1, -1)),
 'Wxy': ('Wxy', -1, 1, (0, 1), (14, 13), (-1, -1)),
 'Wxz': ('Wxz', -1, 1, (0, 2), (15, 13), (-1, -1)),
 'Wyz': ('Wyz', -1, 1, (1, 2), (15, 14), (-1, -1))}

In [19]:
from dataclasses import dataclass, asdict


@dataclass
class ModelParameters:
    TxxL: float = 0.0
    TxyL: float = 0.0
    TxzL: float = 0.0
    TyxL: float = 0.0
    TyyL: float = 0.0
    TyzL: float = 0.0
    TzxL: float = 0.0
    TzyL: float = 0.0
    TzzL: float = 0.0
    RxxL: float = 0.0
    RxyL: float = 0.0
    RxzL: float = 0.0
    RyxL: float = 0.0
    RyyL: float = 0.0
    RyzL: float = 0.0
    RzxL: float = 0.0
    RzyL: float = 0.0
    RzzL: float = 0.0
    Wxy: float = 0.0
    Wxz: float = 0.0
    Wyz: float = 0.0

In [21]:
params = ModelParameters()
params

ModelParameters(TxxL=0.0, TxyL=0.0, TxzL=0.0, TyxL=0.0, TyyL=0.0, TyzL=0.0, TzxL=0.0, TzyL=0.0, TzzL=0.0, RxxL=0.0, RxyL=0.0, RxzL=0.0, RyxL=0.0, RyyL=0.0, RyzL=0.0, RzxL=0.0, RzyL=0.0, RzzL=0.0, Wxy=0.0, Wxz=0.0, Wyz=0.0)

In [22]:
p = list(asdict(params).values())
type(p), p

(list,
 [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0])

In [24]:
params.TxxL

0.0

In [25]:
params["TxxL"]

TypeError: 'ModelParameters' object is not subscriptable

In [26]:
asdict(params)["TxxL"]

0.0

In [27]:
d = asdict(params)
d

{'TxxL': 0.0,
 'TxyL': 0.0,
 'TxzL': 0.0,
 'TyxL': 0.0,
 'TyyL': 0.0,
 'TyzL': 0.0,
 'TzxL': 0.0,
 'TzyL': 0.0,
 'TzzL': 0.0,
 'RxxL': 0.0,
 'RxyL': 0.0,
 'RxzL': 0.0,
 'RyxL': 0.0,
 'RyyL': 0.0,
 'RyzL': 0.0,
 'RzxL': 0.0,
 'RzyL': 0.0,
 'RzzL': 0.0,
 'Wxy': 0.0,
 'Wxz': 0.0,
 'Wyz': 0.0}

In [28]:
d.TxxL

AttributeError: 'dict' object has no attribute 'TxxL'

In [1]:
import cmm_error_map.design_matrix_linear_fixed as design

In [2]:
design.model_parameters_dict

{'TxxL': 0.0,
 'TxyL': 0.0,
 'TxzL': 0.0,
 'TyxL': 0.0,
 'TyyL': 0.0,
 'TyzL': 0.0,
 'TzxL': 0.0,
 'TzyL': 0.0,
 'TzzL': 0.0,
 'RxxL': 0.0,
 'RxyL': 0.0,
 'RxzL': 0.0,
 'RyxL': 0.0,
 'RyyL': 0.0,
 'RyzL': 0.0,
 'RzxL': 0.0,
 'RzyL': 0.0,
 'RzzL': 0.0,
 'Wxy': 0.0,
 'Wxz': 0.0,
 'Wyz': 0.0}

In [3]:
list(design.model_parameters_dict.values())

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [7]:
i = 5
f"abc {i:02d}"

'abc 05'

In [11]:
start = -5.0
stop = 5.0
step = 0.1
span = np.arange(start, stop + step, step)

In [13]:
v = 2
int(np.argmin(np.abs(span - v)))

70

In [16]:
np.argmin(np.abs(span - v))


70

In [18]:
dn = {
    "a": {"value": 0.0, "slide_factor": 1e-8},
    "b": {"value": 0.0, "slide_factor": 1e-8},
    "c": {"value": 0.0, "slide_factor": 1e-8},
    "d": {"value": 0.0, "slide_factor": 1e-5},
}

In [20]:
[d["slide_factor"] for d in dn.values()]

[1e-08, 1e-08, 1e-08, 1e-05]

In [10]:
span = np.arange(1, 4.1, 0.25)
span

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  ])

In [11]:
10**span

array([   10.        ,    17.7827941 ,    31.6227766 ,    56.23413252,
         100.        ,   177.827941  ,   316.22776602,   562.34132519,
        1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [17]:
x = np.array([1, 2, 5, 7.5])
np.hstack((x, x * 10, x * 100, x * 1000, [10000]))

array([1.0e+00, 2.0e+00, 5.0e+00, 7.5e+00, 1.0e+01, 2.0e+01, 5.0e+01,
       7.5e+01, 1.0e+02, 2.0e+02, 5.0e+02, 7.5e+02, 1.0e+03, 2.0e+03,
       5.0e+03, 7.5e+03, 1.0e+04])

In [18]:
x = "Txx"
y = "sld_" + x
y[:3]

'sld'

In [1]:
model_parameters_dict = {
    "Txx": 0.0,
    "Txy": 0.0,
    "Txz": 0.0,
    "Tyx": 0.0,
    "Tyy": 0.0,
    "Tyz": 0.0,
    "Tzx": 0.0,
    "Tzy": 0.0,
    "Tzz": 0.0,
    "Rxx": 0.0,
    "Rxy": 0.0,
    "Rxz": 0.0,
    "Ryx": 0.0,
    "Ryy": 0.0,
    "Ryz": 0.0,
    "Rzx": 0.0,
    "Rzy": 0.0,
    "Rzz": 0.0,
    "Wxy": 0.0,
    "Wxz": 0.0,
    "Wyz": 0.0,
}

In [4]:
params = np.zeros(21)
params[0] = 1.33e-05
params[3] = -1.12e-05
params[4] = -5.09e-06
params[6] = 2.6e-05
params[7] = 4.6e-06
params[8] = 3.34e-08
params[9] = 7.49e-09
params[10] = 1.54e-08
params[11] = 5e-09
params[12] = -4.58e-09
params[13] = -1.43e-08
params[14] = 2.19e-08
params[15] = 2.49e-09
params[16] = -7.94e-10
params[17] = 4.78e-08


In [6]:
d = {key: value for key, value in zip(model_parameters_dict.keys(), params)}
d

{'Txx': 1.33e-05,
 'Txy': 0.0,
 'Txz': 0.0,
 'Tyx': -1.12e-05,
 'Tyy': -5.09e-06,
 'Tyz': 0.0,
 'Tzx': 2.6e-05,
 'Tzy': 4.6e-06,
 'Tzz': 3.34e-08,
 'Rxx': 7.49e-09,
 'Rxy': 1.54e-08,
 'Rxz': 5e-09,
 'Ryx': -4.58e-09,
 'Ryy': -1.43e-08,
 'Ryz': 2.19e-08,
 'Rzx': 2.49e-09,
 'Rzy': -7.94e-10,
 'Rzz': 4.78e-08,
 'Wxy': 0.0,
 'Wxz': 0.0,
 'Wyz': 0.0}

In [2]:
x = np.array([1.,2.,3.])
type(x)

numpy.ndarray

In [3]:
np.linalg.norm(x)

3.7416573867739413

In [4]:
xn = x/np.linalg.norm(x)
xn

array([0.26726124, 0.53452248, 0.80178373])

In [6]:
np.linalg.norm(xn)

1.0

In [13]:
y = np.array([4,5,6])
z = np.array([7,8,9])
t = np.array([0,1,2])

In [15]:
m1 = np.vstack((x,y,z,t)).T
m1

array([[1., 4., 7., 0.],
       [2., 5., 8., 1.],
       [3., 6., 9., 2.]])

In [16]:
np.vstack((m1, [0,0,0,1]))

array([[1., 4., 7., 0.],
       [2., 5., 8., 1.],
       [3., 6., 9., 2.],
       [0., 0., 0., 1.]])

In [28]:
import mathutils as mu

In [2]:
mu.Vector()

Vector((0.0, 0.0, 0.0))

In [3]:
mu.Matrix()

Matrix(((1.0, 0.0, 0.0, 0.0),
        (0.0, 1.0, 0.0, 0.0),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))

In [81]:
# data classes with mutable list
from dataclasses import dataclass, field
@dataclass
class SomeClass:
    some_list: list = field(default_factory=list[str])

In [82]:
d1 = SomeClass(some_list=['a','b','c'])
d2 = SomeClass(some_list=['1','2','3'])

In [83]:
d1.some_list

['a', 'b', 'c']

In [84]:
d2.some_list

['1', '2', '3']

In [85]:
d1.some_list.append('d')
d1

SomeClass(some_list=['a', 'b', 'c', 'd'])

In [86]:
d2

SomeClass(some_list=['1', '2', '3'])

In [87]:
d3=SomeClass()
d3

SomeClass(some_list=[])

In [88]:
d3.some_list

[]

In [24]:
my_dict = {}
my_dict["a1"] = my_dict.get("a1", SomeClass())

In [25]:
my_dict

{'a1': SomeClass(some_list=[])}

In [26]:
my_dict["a1"] = d1
my_dict["a1"] = my_dict.get("a1", SomeClass())
my_dict


{'a1': SomeClass(some_list=['a', 'b', 'c', 'd'])}

In [27]:
my_dict["b2"] = my_dict.get("b2", SomeClass())
my_dict

{'a1': SomeClass(some_list=['a', 'b', 'c', 'd']),
 'b2': SomeClass(some_list=[])}

In [69]:
x0 , x1, x2  = 1, 2, 0
z0 , z1, z2  = 0, 0, 1
p0,p1,p2 = 10, 20, 30

In [61]:

x = mu.Vector((x0,x1,x2)).normalized()
x

Vector((0.4472135901451111, 0.8944271802902222, 0.0))

In [62]:
z = mu.Vector((z0,z1,z2)).normalized()
z

Vector((0.0, 0.0, 1.0))

In [63]:
y = x.cross(z)
y

Vector((0.8944271802902222, -0.4472135901451111, 0.0))

In [70]:
p = mu.Vector((p0,p1,p2))
p

Vector((10.0, 20.0, 30.0))

In [66]:
mat = mu.Matrix([x,y,z])
mat, mat.transposed()

(Matrix(((0.4472135901451111, 0.8944271802902222, 0.0),
         (0.8944271802902222, -0.4472135901451111, 0.0),
         (0.0, 0.0, 1.0))),
 Matrix(((0.4472135901451111, 0.8944271802902222, 0.0),
         (0.8944271802902222, -0.4472135901451111, 0.0),
         (0.0, 0.0, 1.0))))

In [68]:
mat.is_orthogonal_axis_vectors

True

In [71]:
mat4 = mu.Matrix.LocRotScale(p,mat, None)
mat4

Matrix(((0.4472135901451111, 0.8944271802902222, 0.0, 10.0),
        (0.8944271802902222, -0.4472135901451111, 0.0, 20.0),
        (0.0, 0.0, 1.0, 30.0),
        (0.0, 0.0, 0.0, 1.0)))

In [74]:
np.array(mat4)

array([[ 0.44721359,  0.89442718,  0.        , 10.        ],
       [ 0.89442718, -0.44721359,  0.        , 20.        ],
       [ 0.        ,  0.        ,  1.        , 30.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [76]:
xt, yt, zt = p
xt

10.0

In [77]:
np.deg2rad(1)

0.017453292519943295

In [78]:
180 * np.deg2rad(1)

3.141592653589793

In [79]:
pd = {}
pd.values()

dict_values([])

In [80]:
for p in pd.values():
    print('hello')

In [90]:
d = {'a':1}
if 'b' in d:
    print("here I am")

In [1]:
532/4

133.0

In [3]:
332/4

83.0

In [41]:
nballs = (3,3)
ballspacing = 1.0

ball_count = nballs[0] * nballs[1]
ballnumber = np.arange(ball_count)

xp = (ballnumber % nballs[0]) * ballspacing
yp = (ballnumber // nballs[1]) * ballspacing


In [42]:
xp, yp

(array([0., 1., 2., 0., 1., 2., 0., 1., 2.]),
 array([0., 0., 0., 1., 1., 1., 2., 2., 2.]))

In [43]:
yp

array([0., 0., 0., 1., 1., 1., 2., 2., 2.])

In [44]:
xyz1 = np.stack((xp,yp,np.zeros_like(xp), np.ones_like(xp)))
xyz1.shape

(4, 9)

In [1]:
import mathutils as mu
import math

In [48]:
mat_rot = mu.Matrix.Rotation(math.radians(90.0), 4, 'Z')
mat_rot

Matrix(((7.549790126404332e-08, -1.0, 0.0, 0.0),
        (1.0, 7.549790126404332e-08, 0.0, 0.0),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))

In [49]:
pts = np.array(mat_rot) @ xyz1
pts.shape


(4, 9)

In [50]:
pts

array([[ 0.00000000e+00,  7.54979013e-08,  1.50995803e-07,
        -1.00000000e+00, -9.99999925e-01, -9.99999849e-01,
        -2.00000000e+00, -1.99999992e+00, -1.99999985e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         7.54979013e-08,  1.00000008e+00,  2.00000008e+00,
         1.50995803e-07,  1.00000015e+00,  2.00000015e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [51]:
xyz1

array([[0., 1., 2., 0., 1., 2., 0., 1., 2.],
       [0., 0., 0., 1., 1., 1., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
pts[:,2]

array([1.50995803e-07, 2.00000000e+00, 0.00000000e+00, 1.00000000e+00])

In [ ]:
# check pyqt QTransform against Blender mathutils

In [4]:
bl_eul =mu.Euler(mu.Vector((1,1,1))).to_matrix()
bl_eul

Matrix(((0.2919265925884247, -0.0720750093460083, 0.9537211656570435),
        (0.4546487033367157, 0.8877497911453247, -0.0720750093460083),
        (-0.8414709568023682, 0.4546487033367157, 0.2919265925884247)))

In [1]:
from PySide6.QtGui import QMatrix4x4, QQuaternion, QVector3D, QTransform


In [2]:
mat = QMatrix4x4()
mat

PySide6.QtGui.QMatrix4x4((1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1))

In [9]:
q1 = QQuaternion().fromEulerAngles(0,0,1.5)
q1

PySide6.QtGui.QQuaternion(0.999914, 0.000000, 0.000000, 0.013090)

In [10]:
q1.toRotationMatrix()

PySide6.QtGui.QMatrix3x3((0.999657, -0.0261769, 0, 0.0261769, 0.999657, 0, 0, 0, 1))

In [12]:
import mathutils as mu
import math

In [33]:
e1_rad = [0.0,0.0,np.pi/2]
e1_deg = np.rad2deg(e1_rad)


In [35]:
mu.Euler(e1_rad).to_matrix()

Matrix(((-4.371138828673793e-08, -1.0, 0.0),
        (1.0, -4.371138828673793e-08, 0.0),
        (-0.0, 0.0, 1.0)))

In [36]:
QQuaternion.fromEulerAngles(e1_deg[2], e1_deg[0], e1_deg[1]).toRotationMatrix()

PySide6.QtGui.QMatrix3x3((1, 0, 0, 0, 5.96046e-08, -1, 0, 1, 5.96046e-08))

In [38]:
mu.Euler( [0, 0, np.deg2rad(90)]).to_matrix()

Matrix(((-4.371138828673793e-08, -1.0, 0.0),
        (1.0, -4.371138828673793e-08, 0.0),
        (-0.0, 0.0, 1.0)))

In [39]:
mu.Euler( [np.deg2rad(10), np.deg2rad(20), np.deg2rad(30)]).to_matrix()

Matrix(((0.813797652721405, -0.4409696161746979, 0.3785223066806793),
        (0.46984633803367615, 0.882564127445221, 0.018028317019343376),
        (-0.3420201241970062, 0.16317591071128845, 0.9254165887832642)))

In [40]:
from pyqtgraph import Transform3D

In [48]:
tr = Transform3D()
tr.setToIdentity()
tr.rotate(10, 1, 0, 0)
tr.rotate(20, 0, 1, 0)
tr.rotate(30, 0, 0, 1)
tr.translate(0,0,0)
tr.matrix()

array([[ 0.81379765, -0.46984631,  0.34202012,  0.        ],
       [ 0.54383814,  0.82317293, -0.16317591,  0.        ],
       [-0.2048741 ,  0.31879574,  0.92541653,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [51]:
v1 = QVector3D()

In [52]:
x,y,z = v1.x(), v1.y(), v1.z() 

In [53]:
y

0.0

In [54]:
QVector3D(1,2,3)

PySide6.QtGui.QVector3D(1.000000, 2.000000, 3.000000)

In [4]:
for i in range(11):
    print(f"{i:02d}")

00
01
02
03
04
05
06
07
08
09
10


In [5]:

d1 = {"A": "a1", "B": "b1", "C": "c1"}
c1 = ["A", "C"]
n1 = [d1[c] for c in c1]
n1

['a1', 'c1']

In [ ]:
for mmt_name, mmt in self.machine.measurements.items():
    if mmt.title in self.mmts_to_plot.value():
        

